-- AlterTable
ALTER TABLE `task` ADD COLUMN `assignedId` BIGINT NULL,
    ADD COLUMN `category` ENUM('GENERAL', 'BUG', 'FEATURE', 'SUPPORT', 'MAINTENANCE') NOT NULL DEFAULT 'GENERAL',
    ADD COLUMN `priority` ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT') NOT NULL DEFAULT 'MEDIUM',
    ADD COLUMN `reporterId` BIGINT NULL;

-- AddForeignKey
ALTER TABLE `Task` ADD CONSTRAINT `Task_assignedId_fkey` FOREIGN KEY (`assignedId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Task` ADD CONSTRAINT `Task_reporterId_fkey` FOREIGN KEY (`reporterId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
